### ISSUE TITLE
Additional column of data needed

### ISSUE THREAD

**Issue by guillermokrh** [NatashaRice2018/CS-424---Project-2#30]
I need the column that has the 3-letter airport code for the Destination airport.  We have 3-letter code for "ORIGIN" but not for Destination, and I need this to complete the "table and chart showing the number of flights for the most common 15 arrival and destination airports".  This would entail making new csv files, so we might want to take a look to make sure we're not missing other data before we download more csv files.

**Comment by mimiyang** [comment]
@guillermokrh  The column name "DEST"  in tem3 is for Destination.
