### ISSUE TITLE
0:00 AM/PM in charts after switching time types.

### ISSUE THREAD

**Issue by NatashaRice2018** [NatashaRice2018/CS-424---Project-2#31]

**Comment by NatashaRice2018** [comment]
@guillermokrh  I fixed this and committed it to another branch. Let me know when the best time to merge it into the master branch is.

**Comment by guillermokrh** [comment]
Thanks! You can merge it now, I just pushed all my latest changes.  I'm going to make sure I'm doing my work on a separate branch, so feel free to push  & merge when you need to, so we don't have to give a heads up.
