### ISSUE TITLE
Arrivals & Departures By Hour and Delays By Hour Tables Not Displaying

### ISSUE THREAD

**Issue by guillermokrh** [NatashaRice2018/CS-424---Project-2#32]
The "Arrivals & Departures By Hour" table in the "Arrivals & Departures" tab and the "Delays Per Hour" table in the "Delays" tab aren't displaying anymore.  This could be because I was trying to add an individual drop-down menu for 12hour/24hour time for each tab, but I tried changing all the code related to time back, and it still isn't working.  I must have omitted something, or not understood how the 12hour/24hour time functions work.

**Comment by mimiyang** [comment]
Table can display Arrivals & Departures By Hour  now
